### ISSUE TITLE
After version 4.4.3 (v4.5.0) an error occurs: string.trimStart is not a function

### ISSUE THREAD

**Issue by kaesar** [riot/compiler#129]
Hi, congrats by this great library (or framework) ...
After version 4.4.3 (v4.5.0) an error occurs: `string.trimStart is not a function`

I first tried with a `package.json`, like this:
```javascript
  "devDependencies": {
    "@babel/core": "^7.6.3",
    "@babel/preset-env": "^7.6.3",
    "@riotjs/compiler": "4.4.3",
    "@riotjs/webpack-loader": "^4.0.1",
    "riot": "^4.6.5",
    "webpack": "^4.41.0",
    "webpack-cli": "^3.3.9"
  },
```
It works fine. The error occurs when change to `"@riotjs/compiler": "4.5.0",`, even with version 4.5.1 I get this:
```
ERROR in ./src/app/views/bit/my-tag.riot
Module build failed (from ./node_modules/@riotjs/webpack-loader/dist/riot-webpack-loader.cjs.js):
TypeError: string.trimStart is not a function
    at node.expressions.reduce (/home/andrey/onmind/asi/node_modules/@riotjs/compiler/dist/index.js:7651:38)
    at Array.reduce (<anonymous>)
    at generateLiteralStringChunksFromNode (/home/andrey/onmind/asi/node_modules/@riotjs/compiler/dist/index.js:7646:27)
    at mergeNodeExpressions (/home/andrey/onmind/asi/node_modules/@riotjs/compiler/dist/index.js:7674:28)
    at createTextExpression (/home/andrey/onmind/asi/node_modules/@riotjs/compiler/dist/index.js:7714:9)
    at createExpression (/home/andrey/onmind/asi/node_modules/@riotjs/compiler/dist/index.js:7739:12)
    at childrenNodes.filter.filter.map.node (/home/andrey/onmind/asi/node_modules/@riotjs/compiler/dist/index.js:8401:18)
    at Array.map (<anonymous>)
    at createTextNodeExpressions (/home/andrey/onmind/asi/node_modules/@riotjs/compiler/dist/index.js:8401:6)
    at createSimpleBinding (/home/andrey/onmind/asi/node_modules/@riotjs/compiler/dist/index.js:8424:12)
    at createTagWithBindings (/home/andrey/onmind/asi/node_modules/@riotjs/compiler/dist/index.js:8646:30)
    at createDynamicNode (/home/andrey/onmind/asi/node_modules/@riotjs/compiler/dist/index.js:8614:12)
    at parseNode (/home/andrey/onmind/asi/node_modules/@riotjs/compiler/dist/index.js:8661:10)
    at build (/home/andrey/onmind/asi/node_modules/@riotjs/compiler/dist/index.js:8701:36)
    at childrenNodes.forEach.node (/home/andrey/onmind/asi/node_modules/@riotjs/compiler/dist/index.js:8712:35)
    at Array.forEach (<anonymous>)
 @ ./src/app/scripts/app.js 2:0-51 17:29-37
```
`my-tag.riot` file contains this:
```html
<my-tag>
    <button>
        <i class="fa icon"></i>
        { state.title }
    </button>

    <script>
        export default {
            state: { title: 'Ok' }
        }
    </script>
</my-tag>
```
Babel file `.babelrc` contains this:
```
{
  "presets": [
    ["@babel/env", {
      "targets": {
        "esmodules": true
      }
    }]
  ]
}
```
The Riot version used is 4.6.5 in any case (Webpack version 4.41.0) under Linux Ubuntu 16.04, but it works fine with the compiler of version 4.4.3
Thanks

**Comment by kaesar** [comment]
I found this works with compiler of version 4.5.1 if I use `<span>` with the expression in `my-tag.riot`, like this:
```html
<my-tag>
    <button>
        <i class="fa icon"></i>
        <span>{ state.title }</span>
    </button>

    <script>
        export default {
            state: { title: 'Ok' }
        }
    </script>
</my-tag>
```
May be is something about the expressions but to migrate this sounds crazy.

**Comment by GianlucaGuarini** [comment]
@kaesar the Riot.js compiler supports [^10.0.0 node](https://github.com/riot/compiler/blob/master/.travis.yml#L4) you are probably using an older node version. Please update your node version to fix the issue.

**Comment by kaesar** [comment]
That's right. I was using node version 8.16. Thanks a lot, have a great week.
