### ISSUE TITLE
SyntaxError: 'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by btakita** [riot/compiler#47]
i'm attempting to use `import` in the script tag.

```javascript
<test-tag>
  <p>Test Tag</p>
  <script>
    import {log} from "../log";
  </script>
</test-tag>
```

got the following:

```
events.js:142
      throw er; // Unhandled 'error' event
      ^

SyntaxError: 'import' and 'export' may only appear at the top level (3:4) while parsing file: /test-project/test-tag.tag
    at Parser.pp.raise (/test-project/node_modules/acorn/dist/acorn.js:1745:13)
    at Parser.pp.parseStatement (/test-project/node_modules/acorn/dist/acorn.js:2449:29)
    at Parser.pp.parseBlock (/test-project/node_modules/acorn/dist/acorn.js:2692:21)
    at Parser.pp.parseFunctionBody (/test-project/node_modules/acorn/dist/acorn.js:1413:22)
    at Parser.pp.parseFunction (/test-project/node_modules/acorn/dist/acorn.js:2770:8)
    at Parser.pp.parseExprAtom (/test-project/node_modules/acorn/dist/acorn.js:1129:19)
    at Parser.pp.parseExprSubscripts (/test-project/node_modules/acorn/dist/acorn.js:1023:19)
    at Parser.pp.parseMaybeUnary (/test-project/node_modules/acorn/dist/acorn.js:1004:19)
    at Parser.pp.parseExprOps (/test-project/node_modules/acorn/dist/acorn.js:948:19)
    at Parser.pp.parseMaybeConditional (/test-project/node_modules/acorn/dist/acorn.js:930:19)
```

**Comment by GianlucaGuarini** [comment]
@btakita use https://github.com/riot/babel-preset-es2015-riot or just read the documentation about babel 6 http://riotjs.com/guide/compiler/#babel-6

**Comment by btakita** [comment]
i'm using `babel-preset-es2015-riot`.

i can't get it to work with the instructions you provided. some things are unclear.

```json
{
  "plugins": [
    ["transform-es2015-modules-commonjs", { "allowTopLevelThis": true }]
  ]
}
```

which configuration is this for? babel? riotify?

is there a canonical example to use compile `riot` tag files in `browserify`? there's a few things on google, none of which seems to work.

**Comment by GianlucaGuarini** [comment]
@btakita check https://github.com/GianlucaGuarini/riot-webpack-babel-template browserify should work in the same way I guess

**Comment by btakita** [comment]
switching to webpack fixed the issue. thank you for the suggestion!

**Comment by btakita** [comment]
In case if anybody is interested, here are the scripts that I'm using

https://github.com/ctx-core/ctx-core/tree/master/sass
