### ISSUE TITLE
resolveModuleSource must be a function

### ISSUE THREAD

**Issue by debackerl** [riot/compiler#73]
Hello,

In riot-compiler's source code, you pass option 'resolveModuleSource' to babel as a string:

https://github.com/riot/compiler/blob/master/lib/parsers/es6.js#L25

If you check Babel's documentation it must be a function:

https://babeljs.io/docs/usage/options/

You can see in their source code that they indeed use this option as a function:

https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/file/index.js#L248

And that's the reason why I'm getting an error:

`TypeError: unknown: resolveModuleSource is not a function

    at File.resolveModuleSource (/mnt/data/home/laurent/riotjs/riot-test/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:343:39)
    at NodePath.enter (/mnt/data/home/laurent/riotjs/riot-test/node_modules/babel/node_modules/babel-core/lib/transformation/modules/lib/metadata.js:29:42)
    at NodePath.call (/mnt/data/home/laurent/riotjs/riot-test/node_modules/babel/node_modules/babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (/mnt/data/home/laurent/riotjs/riot-test/node_modules/babel/node_modules/babel-core/lib/traversal/path/context.js:90:8)
    at TraversalContext.visitMultiple (/mnt/data/home/laurent/riotjs/riot-test/node_modules/babel/node_modules/babel-core/lib/traversal/context.js:108:16)
    at TraversalContext.visit (/mnt/data/home/laurent/riotjs/riot-test/node_modules/babel/node_modules/babel-core/lib/traversal/context.js:146:19)
    at Function.traverse.node (/mnt/data/home/laurent/riotjs/riot-test/node_modules/babel/node_modules/babel-core/lib/traversal/index.js:76:17)
    at Object.traverse [as default] (/mnt/data/home/laurent/riotjs/riot-test/node_modules/babel/node_modules/babel-core/lib/traversal/index.js:55:14)
    at NodePath.traverse (/mnt/data/home/laurent/riotjs/riot-test/node_modules/babel/node_modules/babel-core/lib/traversal/path/index.js:163:23)
    at CommonJSFormatter.getMetadata (/mnt/data/home/laurent/riotjs/riot-test/node_modules/babel/node_modules/babel-core/lib/transformation/modules/_default.js:129:22)
`

I have installed babel 5.8.38 (because your comment in the source code suggest you don't support newer versions of babel).

Am I mistaken? Thank you

**Comment by GianlucaGuarini** [comment]
babel5 is still supported using `type: es6` for babel6 you need to use `type babel` more info here http://riotjs.com/guide/compiler/#ecmascript-6

**Comment by debackerl** [comment]
@GianlucaGuarini, if you read my initial report, you can see that I'm using babel 5.8.38 + the es6 parser (es6.js), so I already did what you just asked.

Using Riot 2.2.4 + Riotify 0.1.2 my project used to work, but since I upgraded to Riot 2.4.1, it fails (using Riotify 0.1.2 or 1.0.1). I double checked, the only difference in my package.json, was version of riot, and I have already provided you with what's wrong in my first post, because babel 5.8.38 is using resolveModuleSource that way

`if (resolveModuleSource) source = resolveModuleSource(source, this.opts.filename);`

**Comment by debackerl** [comment]
BTW, the bug in your code only shows up when somebody is doing an 'import' in the script part of a tag when using es6. So it's possible that many people don't see it.
